### ISSUE TITLE
Error in console output

### ISSUE THREAD

**Issue by obrejla** [anacierdem/vscode-requirejs#11]
Hi,
saw this in CDT:
```
Cannot read property '2' of null: TypeError: Cannot read property '2' of null
    at referenceProvider.provideDefinition (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.25/extension.js:124:45)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6406
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17664
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13768)
    at Object.h [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17627)
    at e.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6360)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16675
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:15295)
    at t.$provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16637)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:20690)
```

**Comment by anacierdem** [comment]
385392cc796048aef64c550a86f330697d0e3b8f should fix that. Version 0.0.26.

**Comment by anacierdem** [comment]
Could you please verify?

**Comment by obrejla** [comment]
Didn't see this anymore. Saw another error :) Will file a separate issue. Thanks.
