### ISSUE TITLE
Error in console output

### ISSUE THREAD

**Issue by obrejla** [anacierdem/vscode-requirejs#12]
Hi,

saw this in CDT:
```
shell.ts:426 Cannot read property '1' of null: TypeError: Cannot read property '1' of null
    at resolve (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.28/extension.js:201:54)
    at referenceProvider.provideDefinition (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.28/extension.js:145:28)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6406
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17664
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13768)
    at Object.h [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17627)
    at e.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6360)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16675
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:15295)
    at t.$provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16637)
```
Thanks!

**Comment by anacierdem** [comment]
This is probably fixed by version 0.0.31. Could you inform if you see it again?
