### ISSUE TITLE
Error when module has no name

### ISSUE THREAD

**Issue by obrejla** [anacierdem/vscode-requirejs#2]
Hi,

Go to Definition does not work on Bar:
```
define([
    'foo/bar/Baz'
], function () {
    // code
});
```
And the error is:
```
TypeError: Cannot read property 'toString' of undefined
    at define (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.11/extension.js:25:33)
    at eval (eval at <anonymous> (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.11/extension.js:74:17), <anonymous>:1:1)
    at referenceProvider.provideDefinition (/Users/ondrejbrejla/.vscode/extensions/lici.require-js-0.0.11/extension.js:74:17)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6406
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17664
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13768)
    at Object.h [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17627)
    at e.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6360)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16675
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:15295)
```

Thanks!

**Comment by obrejla** [comment]
And also Go to Definition when "ctrl+click" on "Bar" does not work.

**Comment by anacierdem** [comment]
Committed 05a758e39105344332b92f0b13dbfb2dc8d01087. This add support for no-name modules. Could you verify now?

**Comment by obrejla** [comment]
Still does not work, but with different error ;)

```
Invalid uri. Scheme and authority or path must be set.
shell.ts:426 Invalid uri. Scheme and authority or path must be set.e.onUnexpectedError @ shell.ts:426(anonymous function) @ shell.ts:383e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by anacierdem** [comment]
Could you provide sample files that you expect to work?

**Comment by obrejla** [comment]
Version 0.0.16...still errors...

```
shell.ts:426 moduleName is not defined: ReferenceError: moduleName is not defined
    at referenceProvider.provideDefinition (/Users/ondrej/.vscode/extensions/lici.require-js-0.0.16/extension.js:142:37)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6406
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17664
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13768)
    at Object.h [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17627)
    at e.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:6360)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16675
    at t._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:15295)
    at t.$provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:16637)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:20690)
```

file is simple...as I described in previous isues:
```
define([
    'base/js/Foo'
], function (
    Foo
    ) {
});
```
I have a custom setting: `"requireModuleSupport.modulePath": "./public_html/modules",`

I hope it's relative to workdir.

Under modules dir there is `base/js/Foo.js` and e.g. `foo.dt/js/Example.js` which has the code above inside.

Thanks.

**Comment by anacierdem** [comment]
It's not relative to workdir, but it's a good idea :) Currently it is absolute path. Could you test with an absolute path tomake sure problem is there?

**Comment by obrejla** [comment]
Lol :D You should definitely write it somewhere ;) But it doesn't work either. It fires error mentions in issue #5

**Comment by anacierdem** [comment]
Fixed and mentioned in README. e0e521fff249160803a6f506ce02e0ded330bffd and 29a1c416f2eb0c2d697c7815669c10a207a38995 committed. Version: 0.0.18

**Comment by obrejla** [comment]
It works for some modules, but does not work for another :) I can not see any difference in their definition...just some works and some don't. In console, there is no error, just a warning which says that: "extensionHost.ts:282 [Extension Host] TextEditor disposed"
Nothing else :/

**Comment by obrejla** [comment]
Is it possible that the problem is, that in a target file, there is no construct like "new TargetFileName"? but that's not needed, constructor function just could be returned without instantiation. And also...what one really wants to, when ctrl+clicking on a module name, is just to open file...does not need the caret on constructor function. Despite the fact that the name used in the file could be absolutely different than the filename itself.

**Comment by anacierdem** [comment]
Committed 54e62a7a7baa6a428c6de5edac85e0705c7c84da and f3b243963b8e7629810fe9358f3202aaf1a62b57. new keyword were required in the referencing file previously. This requirement is now removed. Added an option "onlyNavigateToFile" to prevent searching in the module file. There are further improvements that will improve stability among different module definitions. Version 0.0.20

**Comment by anacierdem** [comment]
Remaining issue is mentioned in #3.
